projects:
    - name: artifactory-front-end
      repoType: npm
      stages: 
        - dev
        - rc
        - release
      profiles:
        - dev
        - ops
        - devops

    - name: artifactory-back-end
      repoType: maven
      stages: 
        - dev
        - prod
      profiles:
        - dev
        - ops
        - devops        